name: Generate Images from PDFs

on:
  workflow_run:
    workflows: ["Update csv_data.csv with new PDFs"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      recreate:
        description: 'Recreate all images'
        required: false
        default: 'false'

jobs:
  generateImages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Generate PNG images and update CSV
        id: generate_images
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const { execSync } = require('child_process');

            const baseUrl = 'https://raw.githubusercontent.com/${{ github.repository }}/main/';
            const csvFilePath = 'csv_data.csv';
            const metadataFolder = 'metadata';
            const recreateImages = "${{ github.event.inputs.recreate }}" === "true";

            // Ensure the metadata folder exists
            if (!fs.existsSync(metadataFolder)) {
                fs.mkdirSync(metadataFolder);
            }

            const readCSV = (filePath) => {
                const data = fs.readFileSync(filePath, 'utf-8');
                return data.split('\n').map(row => row.split(',')).filter(row => row.length > 1);
            };

            const writeCSV = (filePath, rows) => {
                const csvContent = rows.map(e => e.join(",")).join("\n");
                fs.writeFileSync(filePath, csvContent, 'utf-8');
            };

            const convertPDFToImage = (pdfPath, imagePath) => {
                if (!fs.existsSync(pdfPath)) {
                    console.error(`PDF file not found: ${pdfPath}`);
                    return;
                }
                console.log(`Converting PDF: ${pdfPath} to Image: ${imagePath}`);

                // Using pdftoppm to convert PDF to PNG
                const outputPrefix = path.parse(imagePath).name; // Get the base name without extension
                try {
                    execSync(`pdftoppm "${pdfPath}" "${outputPrefix}" -png -f 1 -l 1`);
                } catch (error) {
                    console.error(`Failed to convert ${pdfPath}: ${error.message}`);
                }
            };

            const rows = readCSV(csvFilePath);
            const headers = rows[0];  // Store the header row for later use
            const csvData = rows.slice(1).map(row => {
                return {
                    id: row[0],
                    title: row[1],
                    categories: row[2],
                    description: row[3],
                    creationDate: row[4],
                    uploadDate: row[5],
                    reportYear: row[6],
                    reportMonth: row[7],
                    pdfUrl: row[8]
                };
            });

            for (const entry of csvData) {
                // Construct paths
                const pdfPath = path.resolve(__dirname, 'pdfs', entry.pdfUrl.split('/').pop());
                const imagePath = path.resolve(metadataFolder, `${entry.id}.png`);

                if (recreateImages || !fs.existsSync(imagePath)) {
                    convertPDFToImage(pdfPath, imagePath);
                }

                entry.imageUrl = baseUrl + path.relative(metadataFolder, imagePath).replace(/\\/g, '/');

                newRows.push(entry);
            }

            writeCSV(csvFilePath, csvData);

      - name: Commit changes to repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add csv_data.csv metadata/
          git commit -m "Update CSV with new image URLs"
          git push
